---
name: Test
run-name: Test something
on:
  push:
    branches:
      - test

jobs:
  test-runner:
    runs-on: self-hosted
    container:
      image: dockette/vercel:latest
    steps:
      - name: run command
        run: vercel --help
