---
name: Test docker
on: workflow_dispatch

jobs:
  test-runner:
    runs-on: self-hosted
    timeout-minutes: 5
    container:
      image: lister169126/php:8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          wget https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-desktop-amd64.iso
