---
name: Vercel docker
run-name: Vercel docker deploy
on: workflow_dispatch

jobs:
  test-runner:
    runs-on: self-hosted
    container:
      image: dockette/vercel:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vercel deploy
        run: |
          args="-t ${{ secrets.VERCEL_API_TOKEN }} -c"
          if [ "${{ secrets.VERCEL_API_TEAM }}" ]; then args+=" --scope ${{ secrets.VERCEL_API_TEAM }}"; fi
          if [ "${{ inputs.ENVIRONMENT }}" = "Production" ]; then args+=" --prod"; fi
          ~/vercel-cli/node_modules/.bin/vercel $args
